### ISSUE TITLE
feature request: provide safelists in tailwind.config

### ISSUE THREAD

**Issue by arily** [daief/daisyui-vue#1]
concatenated class names will not be detected by tailwind according to [this tailwind's document](https://tailwindcss.com/docs/content-configuration#dynamic-class-names).
meanwhile tailwind has an [safelisting](https://tailwindcss.com/docs/content-configuration#safelisting-classes) option to keep those classes from being filtered out.

It would be much more convenient to have some pre-defined safelists for users to import. 
(I would assume that SSR renderes first page without critical styles will also be fixed with this.)

```js
// safelist
export const button = [
    {
      pattern: /btn-.+/
    }
]
```
```js
// tailwind.config.js
const { button } =  require('daisyui-vue/config/safelist')

module.exports = {
  safelist: [
     ...button,
  ]
}
```

**Comment by daief** [comment]
First I am glad you insterest in this project. But I guess you may submit this suggestion to [daisyui](https://github.com/saadeghi/daisyui).

This is a vue3 based library which does not depend on tailwind.

**Comment by arily** [comment]
created an issue for daisyui https://github.com/saadeghi/daisyui/issues/1155
