### ISSUE TITLE
change the name of the prop 'type'

### ISSUE THREAD

**Issue by arily** [daief/daisyui-vue#2]
https://stackoverflow.com/questions/2825856/html-button-to-not-submit-form

form>button has to explicitly set type to `button` to prevent the form from submitting,
but the `type` keyword is already used for picking variants.

please consider changing the key of the `type` prop to something else, maybe something like `variant`

**Comment by daief** [comment]
Thanks for your reminder. I want to add a `htmlType` prop. It is a common way to handle original html type in some other library like [antd](https://ant.design/components/button).

**Comment by arily** [comment]
I would suggest avoiding handling HTML attributes manually, that's a lot of additional work. 
also, the component will be web-component compatible.
bootstrap-vue uses the `variant` keyword to specify the color scheme.

**Comment by daief** [comment]
I can agree with you. But it is customary for many people to use `type` as the theme type control for buttons. I have no intention of changing it. And in my experience, we will hande HTML attributes manually only in a few cases.

**Comment by arily** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
here is the list for html attributes.
By manually handle few selected one you may creating more inconsistent between handled and unhandled attrs.

**Comment by daief** [comment]
Ok. I will change `type` to `variant`.

**Comment by daief** [comment]
Done: <https://github.com/daief/daisyui-vue/commit/b44509ed22d96e1f2d0c368873211f8dc333cff0>
