### ISSUE TITLE
How to style with tailwind?

### ISSUE THREAD

**Issue by andr-ec** [daief/daisyui-vue#6]
I noticed in version `0.0.1-alpha.5` that the tailwind styling from `tailwind.config.js` would transfer over to this library. Then as of version `0.0.1-alpha.6` styling/themes from `tailwind.config.js` including daisy themes don't pass over anymore. Is there a way for those themes to pass over? 

Thanks!

**Comment by AdrDSB** [comment]
@andr-ec As you closed this issues: How did you resolve this?

**Comment by daief** [comment]
@AdrDSB This is a vue3 based library which does not depend on tailwind.  All themes are now built-in so you just need to set `data-theme` attribute of HTML tag. The way to use theme will be improved so that we can reduce theme size or custom theme.
